INSERT INTO `article` VALUES (1, 'What Steps should one take while doing Data Preprocessing?', 'Mohit Sharma', 'In Real world data are generally incomplete: lacking attribute values, lacking certain attributes of interest, or containing only aggregate data. Noisy: containing errors or outliers. Inconsistent: containing discrepancies in codes or names.', '2018-7-25', 'https://hackernoon.com/what-steps-should-one-take-while-doing-data-preprocessing-502c993e1caa');
INSERT INTO `article` VALUES (2, '5 Regression Loss Functions All Machine Learners Should Know', 'Prince Grover', 'Think of loss function like undulating mountain and gradient descent is like sliding down the mountain to reach the bottommost point.', '2018-6-5', 'https://heartbeat.fritz.ai/5-regression-loss-functions-all-machine-learners-should-know-4fb140e9d4b0');
INSERT INTO `article` VALUES (3, 'Supervised and Unsupervised learning', 'Geeks', 'A deep introduction to the difference between supervised and unsupervised learning.', '2018-2-24', 'https://www.geeksforgeeks.org/supervised-unsupervised-learning/');
INSERT INTO `article` VALUES (4, 'A Beginner\'s Guide to Deep Reinforcement Learning', 'A.I. Wiki', 'When it is not in our power to determine what is true, we ought to act in accordance with what is most probable.', '2018-5-11', 'https://skymind.ai/wiki/deep-reinforcement-learning');
INSERT INTO `article` VALUES (5, 'Understanding of Convolutional Neural Network-Deep Learning', 'Prabhu', 'In neural networks, Convolutional neural network (ConvNets or CNNs) is one of the main categories to do images recognition, images classifications. Objects detections, recognition faces etc., are some of the areas where CNNs are widely used.', '2018-3-4', 'https://medium.com/@RaghavPrabhu/understanding-of-convolutional-neural-network-cnn-deep-learning-99760835f148');
INSERT INTO `article` VALUES (6, 'a', 'b', 'c', '2018-8-7', 'd');
INSERT INTO `article` VALUES (7, 'test', 'test', 'test', '2018-12-15', 'test');
INSERT INTO `article` VALUES (8, 'test', 'test', 'test', '2018-12-15', 'test');
INSERT INTO `article` VALUES (9, 'test', 'test', 'test', '2018-12-15', 'test');
